### ISSUE TITLE
Retrieving all prefix matches?

### ISSUE THREAD

**Issue by chrisspen** [jfjlaros/dict-trie#5]
Is there a way to retrieve all keys matching a prefix?

I see there's a `has_prefix` method and a private `_find` method for doing general searching, but there's no way to access it to get the keys found in `has_prefix`. Am I missing something?

**Comment by chrisspen** [comment]
If I'm reading your code correctly, this should be pretty trivial. Something like:

    def get_all_partial_matches(prefix: str, trie: object):
        subnode = _find(trie.root, prefix)
        return _iterate(prefix, subnode)

**Comment by jfjlaros** [comment]
Something like that would do the trick indeed. We need to check some edge cases though (empty prefix, prefix ends in leaf node, prefix not found, etc.) using unit tests.

Would you care to prepare a pull request?

**Comment by chrisspen** [comment]
>Would you care to prepare a pull request?

Sure. How do you run your test suite? I see the pytest requires, but I don't see any scripts or configuration for calling it on your test file.

**Comment by jfjlaros** [comment]
Thanks for the PR, I will have a look at it soon.

Tests are run via [GitHub workflows](https://github.com/jfjlaros/dict-trie/blob/master/.github/workflows/python-package.yml) (or manually via `python -m pytest`).

**Comment by jfjlaros** [comment]
Merged in #6.
